version: "3.8"
services:
  web:
    image: lqwangxg/node
    command: npm run start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - pg-db

  pg-db:
    image: postgres
    ports:
      - "5432:5432"

